cc_library(
    name = "sfc",
    hdrs = [
        "common.hh",
        "circle.hh",
        "esa_campaign.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/container:btree",
        "@highway//:hwy",
    ],
)
