cc_library(
    name = "sfc",
    hdrs = [
        "CEHCDS.hpp",
        "EHCDS.hpp",
        "HCDS.hpp",
        "HCDS_dynamic.hpp",
        "HCDS_logarithmic.hpp",
        "HCDS_map.hpp",
        "HCDS_noranks.hpp",
        "HCDSwoTree.hpp",
        "OHCDS.hpp",
        "SHCDS.hh",
        "common.hh",
        "circle.hh",
        "esa_campaign.hh",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@abseil-cpp//absl/container:btree",
        "@highway//:hwy",
    ],
)
